CREATE TABLE `asset` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `description` text,
  `type_id` int(11) DEFAULT NULL,
  `container_name` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL,
  `ssl_url` varchar(255) DEFAULT NULL,
  `thumb_url` varchar(255) DEFAULT NULL,
  `thumb_ssl_url` varchar(255) DEFAULT NULL,
  `image_thumb_high_quality_url` varchar(255) DEFAULT NULL,
  `image_thumb_high_quality_ssl_url` varchar(255) DEFAULT NULL,
  `image_thumb_low_quality_url` varchar(255) DEFAULT NULL,
  `image_thumb_low_quality_ssl_url` varchar(255) DEFAULT NULL,
  `file_name` varchar(255) DEFAULT NULL,
  `mime_type` varchar(255) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `created_on` datetime NOT NULL,
  `updated_by` int(11) NOT NULL,
  `updated_on` datetime NOT NULL,
  `visibility` enum('public','protected') DEFAULT 'public',
  `storage` enum('cloud_files','local_server') NOT NULL DEFAULT 'cloud_files',
  PRIMARY KEY (`id`),
  KEY `asset_type_id_index` (`type_id`),
  CONSTRAINT `asset_type_id_fk` FOREIGN KEY (`type_id`) REFERENCES `asset_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=940 DEFAULT CHARSET=utf8;